kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sso-patch
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
  source:
    git:
      uri: https://gitlab.cee.redhat.com/aszczucz/rh-sso-container-patch.git
  strategy:
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: sso74-openshift-rhel8:latest
  output:
    to:
      kind: ImageStreamTag
      name: sso-patch:latest
